### PR TITLE
Add separate zip files per platform

### LINKED ISSUE #25: Separate downloads per platform
Related to #24, I use Windows primarily and to solve https://github.com/lensapp/lens/issues/649 kubelogin was the perfect solution. I looked at the releases tab and aside from the source, a single zip is present. I almost glossed over this as a solution because there is no indication that the build artifact contains Windows, Linux and Mac binaries. It would be helpful to indicate it is for all platforms, or separate these into platform specific files.

Thanks!

### PR DESCRIPTION
**Pull request by ocdi**
Fixes #25 

I tested this on my fork and the releases can be seen here https://github.com/ocdi/kubelogin/releases

### CODE REVIEW

**Comment by weinong** [comment]
@ocdi can we keep the old behavior (kubelogin.zip) as azure-cli is taking a dependency on it.

**Comment by ocdi** [comment]
ahhh yes absolutely, I wasn't aware of that reason or usage, will update

**Comment by ocdi** [comment]
I restored the original behaviour and this is how the releases look to me now on my test

image

**Comment by weinong** [comment]
that's great!

**Pull request merged**
