### PR TITLE
Replacing GetMSIVMEndpoint to NewServicePrincipalTokenFromMSI for avoiding custom msi endpoint

### PR DESCRIPTION
**Pull request by skythet**
Fix for: https://github.com/Azure/kubelogin/issues/52

### CODE REVIEW

**Comment by weinong** [comment]
https://github.com/Azure/go-autorest/blob/79a63e70c4d8b2840383d2a8791e41b6830ca9ad/autorest/adal/token.go#L736

`GetMSIEndpoint()` seems to be deprecated. I believe all we need is bump the adal version and `NewServicePrincipalTokenFromMSI()` will automatically pick up the right MSI endpoint. Can you give that a try?

**Comment by weinong** [comment]
in fact, `NewServicePrincipalTokenFromMSI ()` is also deprecated, would you mind refactoring to use `NewServicePrincipalTokenFromManagedIdentity()`?

**Comment by skythet** [comment]
Thanks, @weinong! I missed that. I've refactored my changes and replaced all the calls to NewServicePrincipalTokenFromManagedIdentity. Also verified changed kubelogin in our infrastructure under app service and in VM, everything works well for us.

**Review by weinong — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
