### PR TITLE
update k8s dependencies to v0.21.3

### PR DESCRIPTION
**Pull request by madeleineth**
This change updates `k8s.io/apimachinery`, `k8s.io/cli-runtime`, and `k8s.io/client-go` from v0.17.4 to v0.21.3. (I then ran `go mod tidy` to propagate transitive requirements.)

The motivation of this change is to fix an issue where `tls-server-name` settings in `$KUBECONFIG` were deleted by `kubelogin convert-kubeconfig`, and I noticed some relevant churn in the upstream code. Whatever was causing it appears to have been fixed in the upstream.

Also fix a typo in the name of `convet_test.go`.

Tested with `make test` and also by installing `kubelogin` and confirming it works on my system, and that `tls-server-name` is no longer deleted when running `kubelogin convert-kubeconfig`.

### CODE REVIEW

**Review by davecummings — APPROVED** [review]

**Comment by weinong** [comment]
nice finding on the typo!

**Comment by weinong** [comment]
build failed.
https://github.com/Azure/kubelogin/pull/66/checks?check_run_id=3187759596#step:4:212

**Comment by madeleineth** [comment]
I'd tested on go 1.16; the build used 1.13, and I have a local repro. Looking into it.

**Comment by madeleineth** [comment]
Backing off to version 0.21.3 instead of 0.22.0-rc.0 seems to have gotten it working with both go 1.13 and 1.16 locally for me, and still addresses the motivating `tls-server-name` issue.

**Comment by weinong** [comment]
you can change golang to 1.16, though.
https://github.com/Azure/kubelogin/blob/master/.github/workflows/build.yml#L13
https://github.com/Azure/kubelogin/blob/master/.github/workflows/release.yml#L17

**Pull request merged**
